from tkinter import ttk


class AppInfo(ttk.Labelframe):
    def __init__(self, *args, **kwargs):
        self._args = args
        self._kwargs = kwargs
        self._root = self._args[0]
        super().__init__(*args, **kwargs)

        self.configure(text="info")

        text = (
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
            "info here\n"
        )
        
        label = ttk.Label(self, text=text)
        label.grid(row=0, column=0)

        self.columnconfigure(0, pad=220)
